name: Consulta CEP
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Install Newman-Reporter-Htmlextra
        run: sudo npm install -g newman-reporter-htmlextra
        
      - name: Execute collection
        run: newman run ./postman/collections/NexusAPI.json --reporters cli, -r htmlextra --reporter-htmlextra-export ./newman_report/index.html

      - name: Deploy report to Github Pages
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: newman_report/